cat alight/prefix.js > alight.js
cat alight/fquery.js >> alight.js
cat alight/core.js >> alight.js
cat alight/utilits.js >> alight.js
cat alight/parser.js >> alight.js
cat alight/directives.js >> alight.js
cat alight/drepeat.js >> alight.js
cat alight/filters.js >> alight.js
cat alight/postfix.js >> alight.js
